version: "3.3"
services:
  node-master:
    depends_on:
      - node-slave1
      - node-slave2
    image: cluster-base:latest
    container_name: node-master
    hostname: node-master
    tty: true
    ports:
      - "8088:8088"
      - "50070:50070"
      - "50030:50030"
      - "8080:8080"
      - "8042:8042"
      - "8888:8888"
    volumes:
      - persist-data:/root/lab/
    networks:
      cluster-network:
        aliases: 
          - node-master
  node-slave1:
    image: cluster-base:latest
    container_name: node-slave1
    hostname: node-slave1
    tty: true
    ports:
      - "7042:8042"
    networks:
      cluster-network:
        aliases: 
          - node-slave1
  node-slave2:
    image: cluster-base:latest
    container_name: node-slave2
    hostname: node-slave2
    tty: true
    ports:
      - "9042:8042"
    networks:
      cluster-network:
        aliases: 
          - node-slave2
  api:
    build: ./api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/app/:/usr/src/app/
    ports:
      - 8002:8000
    image: api:latest
    container_name: mongo-api
    hostname: mongo-api
    environment:
      MONGO_DETAILS: mongodb://root:yurt@mongo:27017/local.yield?authSource=local
    networks:
      cluster-network:
        aliases: 
          - mongo-api
  mongo:
    image: mongo
    restart: always
    volumes:
      - persist-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yurt
    networks:
      cluster-network:
        aliases: 
          - mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: yurt
      ME_CONFIG_MONGODB_URL: mongodb://root:yurt@mongo:27017/
    networks:
      cluster-network:
        aliases: 
          - mongo-express
volumes:
  persist-data:
  persist-db:
networks:
  cluster-network:
    driver: bridge
    ipam:
      driver: default