version: "3.1"

services:
  scheduler:
    image: daskdev/dask:latest
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: daskdev/dask:latest
    command: ["dask-worker", "tcp://scheduler:8786"]
    deploy:
      replicas: 2

  notebook:
    image: daskdev/dask-notebook:latest
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
